/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

import * as React from "react";
import { EscapeHatchProps } from "@aws-amplify/ui-react/internal";
import { IconProps, ImageProps, TextProps, ViewProps } from "@aws-amplify/ui-react";
export declare type PrimitiveOverrideProps<T> = Partial<T> & React.DOMAttributes<HTMLDivElement>;
export declare type EditProfileKynOverridesProps = {
    EditProfileKyn?: PrimitiveOverrideProps<ViewProps>;
    "side bar1"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 4"?: PrimitiveOverrideProps<ViewProps>;
    Home?: PrimitiveOverrideProps<ViewProps>;
    Vector1207?: PrimitiveOverrideProps<IconProps>;
    Vector1208?: PrimitiveOverrideProps<IconProps>;
    Notifications1209?: PrimitiveOverrideProps<ViewProps>;
    Vector12010?: PrimitiveOverrideProps<IconProps>;
    Vector12011?: PrimitiveOverrideProps<IconProps>;
    "Calendar today"?: PrimitiveOverrideProps<ViewProps>;
    Vector12013?: PrimitiveOverrideProps<IconProps>;
    Vector12014?: PrimitiveOverrideProps<IconProps>;
    "Show chart"?: PrimitiveOverrideProps<ViewProps>;
    Vector12016?: PrimitiveOverrideProps<IconProps>;
    Vector12017?: PrimitiveOverrideProps<IconProps>;
    Person?: PrimitiveOverrideProps<ViewProps>;
    Vector12019?: PrimitiveOverrideProps<IconProps>;
    Vector12020?: PrimitiveOverrideProps<IconProps>;
    "Group 1"?: PrimitiveOverrideProps<ViewProps>;
    "Ellipse 1"?: PrimitiveOverrideProps<IconProps>;
    Settings12023?: PrimitiveOverrideProps<ViewProps>;
    Group12024?: PrimitiveOverrideProps<ViewProps>;
    Vector12025?: PrimitiveOverrideProps<IconProps>;
    Vector12026?: PrimitiveOverrideProps<IconProps>;
    "side bar2"?: PrimitiveOverrideProps<ViewProps>;
    Settings12028?: PrimitiveOverrideProps<TextProps>;
    "Keyboard arrow left"?: PrimitiveOverrideProps<ViewProps>;
    Vector12030?: PrimitiveOverrideProps<IconProps>;
    Vector12031?: PrimitiveOverrideProps<IconProps>;
    "Group 2"?: PrimitiveOverrideProps<ViewProps>;
    "Edit profile12033"?: PrimitiveOverrideProps<TextProps>;
    Edit?: PrimitiveOverrideProps<ViewProps>;
    Vector12035?: PrimitiveOverrideProps<IconProps>;
    Vector12036?: PrimitiveOverrideProps<IconProps>;
    "Group 3"?: PrimitiveOverrideProps<ViewProps>;
    Notification?: PrimitiveOverrideProps<TextProps>;
    Notifications12039?: PrimitiveOverrideProps<ViewProps>;
    Vector12040?: PrimitiveOverrideProps<IconProps>;
    Vector12041?: PrimitiveOverrideProps<IconProps>;
    "Group 4"?: PrimitiveOverrideProps<ViewProps>;
    Lock?: PrimitiveOverrideProps<ViewProps>;
    Group12044?: PrimitiveOverrideProps<ViewProps>;
    Vector12045?: PrimitiveOverrideProps<IconProps>;
    Vector12046?: PrimitiveOverrideProps<IconProps>;
    Vector12047?: PrimitiveOverrideProps<IconProps>;
    Security?: PrimitiveOverrideProps<TextProps>;
    "Group 5"?: PrimitiveOverrideProps<ViewProps>;
    Settings12050?: PrimitiveOverrideProps<ViewProps>;
    Vector12051?: PrimitiveOverrideProps<IconProps>;
    Vector12052?: PrimitiveOverrideProps<IconProps>;
    Appearance?: PrimitiveOverrideProps<TextProps>;
    "Group 6"?: PrimitiveOverrideProps<ViewProps>;
    "Help outline"?: PrimitiveOverrideProps<ViewProps>;
    Vector12056?: PrimitiveOverrideProps<IconProps>;
    Vector12057?: PrimitiveOverrideProps<IconProps>;
    Help?: PrimitiveOverrideProps<TextProps>;
    "Line 1"?: PrimitiveOverrideProps<IconProps>;
    profile1?: PrimitiveOverrideProps<ViewProps>;
    "unsplash:C8Ta0gwPbQg12061"?: PrimitiveOverrideProps<ImageProps>;
    "Group 7"?: PrimitiveOverrideProps<ViewProps>;
    "Ellipse 2"?: PrimitiveOverrideProps<IconProps>;
    Notifications12064?: PrimitiveOverrideProps<ViewProps>;
    Vector12065?: PrimitiveOverrideProps<IconProps>;
    Vector12066?: PrimitiveOverrideProps<IconProps>;
    "unsplash:C8Ta0gwPbQg12067"?: PrimitiveOverrideProps<ImageProps>;
    "Edit profile12068"?: PrimitiveOverrideProps<TextProps>;
    firstname?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 712070"?: PrimitiveOverrideProps<ViewProps>;
    "First Name"?: PrimitiveOverrideProps<TextProps>;
    "First name"?: PrimitiveOverrideProps<TextProps>;
    city?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 712074"?: PrimitiveOverrideProps<ViewProps>;
    City?: PrimitiveOverrideProps<TextProps>;
    "College Park"?: PrimitiveOverrideProps<TextProps>;
    "Keyboard arrow down12077"?: PrimitiveOverrideProps<ViewProps>;
    Vector12078?: PrimitiveOverrideProps<IconProps>;
    Vector12079?: PrimitiveOverrideProps<IconProps>;
    state?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 812081"?: PrimitiveOverrideProps<ViewProps>;
    State?: PrimitiveOverrideProps<TextProps>;
    Maryland?: PrimitiveOverrideProps<TextProps>;
    "Keyboard arrow down12084"?: PrimitiveOverrideProps<ViewProps>;
    Vector12085?: PrimitiveOverrideProps<IconProps>;
    Vector12086?: PrimitiveOverrideProps<IconProps>;
    Email12087?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 712088"?: PrimitiveOverrideProps<ViewProps>;
    Email12089?: PrimitiveOverrideProps<TextProps>;
    "barbsbailey23@gmail.com"?: PrimitiveOverrideProps<TextProps>;
    "Group 812091"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 912092"?: PrimitiveOverrideProps<ViewProps>;
    Check12093?: PrimitiveOverrideProps<ViewProps>;
    Vector12094?: PrimitiveOverrideProps<IconProps>;
    Vector12095?: PrimitiveOverrideProps<IconProps>;
    Password12096?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 712097"?: PrimitiveOverrideProps<ViewProps>;
    Password12098?: PrimitiveOverrideProps<TextProps>;
    "*********"?: PrimitiveOverrideProps<TextProps>;
    "Group 8120100"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 9120101"?: PrimitiveOverrideProps<ViewProps>;
    Check120102?: PrimitiveOverrideProps<ViewProps>;
    Vector120103?: PrimitiveOverrideProps<IconProps>;
    Vector120104?: PrimitiveOverrideProps<IconProps>;
    address120105?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 7120106"?: PrimitiveOverrideProps<ViewProps>;
    Address?: PrimitiveOverrideProps<TextProps>;
    "33062 Zboncak Isle"?: PrimitiveOverrideProps<TextProps>;
    address120109?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 7120110"?: PrimitiveOverrideProps<ViewProps>;
    "Contact Number"?: PrimitiveOverrideProps<TextProps>;
    "202.937.3258"?: PrimitiveOverrideProps<TextProps>;
    lastname?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 8120114"?: PrimitiveOverrideProps<ViewProps>;
    "Last Name"?: PrimitiveOverrideProps<TextProps>;
    "Last name"?: PrimitiveOverrideProps<TextProps>;
    "Group 9"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 10120118"?: PrimitiveOverrideProps<ViewProps>;
    Cancel?: PrimitiveOverrideProps<TextProps>;
    "Group 10"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 10120121"?: PrimitiveOverrideProps<ViewProps>;
    Save?: PrimitiveOverrideProps<TextProps>;
    "image 7"?: PrimitiveOverrideProps<ImageProps>;
} & EscapeHatchProps;
export declare type EditProfileKynProps = React.PropsWithChildren<Partial<ViewProps> & {
    overrides?: EditProfileKynOverridesProps | undefined | null;
}>;
export default function EditProfileKyn(props: EditProfileKynProps): React.ReactElement;
